### ISSUE TITLE
The results of batch jobs are empty. I wonder if it is an error or I missed something to run.

### ISSUE THREAD

**Issue by Yujuson** [DigitalEarthSweden/digital-earth-sweden-community#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur  version 11.4
 - Browser: FireFow
 - Version: 107.0

**Additional context**
Hi!

I have run some batch jobs on some of OpenEO demo scripts.
The jobs were progressed well with a message of status: send 'start'-queued-running-finished.
However, at job.get_results() the result is empty and comes with an error message. I wonder if I missed something and how I can see the result. 
The name of scripts and error messages are as follows:

1. 3b.NDVI-Bandmath
<img width="938" alt="bild" src="https://user-images.githubusercontent.com/120726072/208105485-d178a66a-de43-4a2a-a736-1ee37c6f1ba6.png">

2. 5.Notebook-Batch-Jobs
<img width="937" alt="bild" src="https://user-images.githubusercontent.com/120726072/208106016-76d42781-6579-4987-8212-4a9b7fd5ea1e.png">

3. 5b.Notebook-Large-Batch-Jobs
<img width="225" alt="bild" src="https://user-images.githubusercontent.com/120726072/208106158-058db525-88a4-47c4-87d4-c56e6239ed17.png">
<img width="936" alt="bild" src="https://user-images.githubusercontent.com/120726072/208106293-2283a163-1bd9-47d8-90e2-634834ddd44d.png">

4. 9.Demo-S3-Using-WQSF-Flags-Mask-Out-Land
<img width="934" alt="bild" src="https://user-images.githubusercontent.com/120726072/208106593-45112132-5cb6-449f-9357-7b2a2f66a8d1.png">

Thank you in advance!

**Comment by danielFlemstrom** [comment]
You should use 
results = job.get_results()
display(results)

To see the results. The name of the file you want to download depends on the contents of the `results`object. Easiest way is to click on the link in the displayed results as shown below:

![image](https://user-images.githubusercontent.com/12410550/208434427-dc5e8d16-0b1b-4740-8cf4-6cb836cfc6a6.png)
